/**
 * AUTO-GENERATED by scripts/generate-design-tokens.ts. Do not edit by hand.
 */

export const Color = {
  BrandYellow: "#faff86",
  BrandCream: "#feffe2",
  BrandGrey: "#f5f5f5",
  BrandDark: "#202621",
  BrandWhite: "#ffffff",
  BrandError: "#ff5f57",
  BrandSuccess: "#35c46b",
  SemanticBackground: "#f5f5f5",
  SemanticForeground: "#202621",
  SemanticCard: "#ffffff",
  SemanticCardForeground: "#202621",
  SemanticPopover: "#ffffff",
  SemanticPopoverForeground: "#202621",
  SemanticPrimary: "#202621",
  SemanticPrimaryForeground: "#ffffff",
  SemanticSecondary: "#faff86",
  SemanticSecondaryForeground: "#202621",
  SemanticMuted: "#feffe2",
  SemanticMutedForeground: "rgb(32 38 33 / 0.62)",
  SemanticAccent: "#faff86",
  SemanticAccentForeground: "#202621",
  SemanticDestructive: "#ff5f57",
  SemanticBorder: "#202621",
  SemanticInput: "#202621",
  SemanticRing: "#202621",
  StatusError: "#ff5f57",
  StatusSuccess: "#35c46b",
} as const;
export type Color = (typeof Color)[keyof typeof Color];

export const Typography = {
  FontFamilyDisplay:
    '"EK Notice Sans", Impact, Haettenschweiler, "Arial Black", sans-serif',
  FontFamilyBody:
    '"Work Sans", "Inter", ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  FontWeightRegular: 400,
  FontWeightBold: 700,
  FontWeightBlack: 900,
  FontSizeXs: "0.625rem",
  FontSizeSm: "0.875rem",
  FontSizeBase: "1rem",
  FontSizeLg: "1.125rem",
  FontSizeXl: "1.25rem",
  FontSize2xl: "1.5rem",
  FontSize3xl: "1.875rem",
  FontSize4xl: "2.25rem",
  FontSize6xl: "3.75rem",
  FontSizeHeadlineMd: "clamp(2rem, 5vw, 3.75rem)",
  FontSizeHeadlineLg: "clamp(2.75rem, 8vw, 5.5rem)",
  FontSizeHeadlineXl: "clamp(3.5rem, 11vw, 7.5rem)",
  LetterSpacingTight: "-0.01em",
  LetterSpacingNormal: "0",
  LetterSpacingWide: "0.18em",
  LetterSpacingWider: "0.25em",
  LineHeightTight: 0.82,
  LineHeightSnug: 0.86,
  LineHeightDisplay: 0.9,
  LineHeightBody: 1.2,
  LineHeightRelaxed: 1.5,
  TextCaseUppercase: "uppercase",
} as const;
export type Typography = (typeof Typography)[keyof typeof Typography];

export const Spacing = {
  "1": "0.25rem",
  "2": "0.5rem",
  "3": "0.75rem",
  "4": "1rem",
  "5": "1.25rem",
  "6": "1.5rem",
  "8": "2rem",
  "10": "2.5rem",
  "12": "3rem",
  "14": "3.5rem",
  "16": "4rem",
} as const;
export type Spacing = (typeof Spacing)[keyof typeof Spacing];

export const Radius = {
  None: "0",
  Sm: "2px",
  Md: "4px",
  Lg: "8px",
  Full: "9999px",
} as const;
export type Radius = (typeof Radius)[keyof typeof Radius];

export const Border = {
  Unveiled: "3px",
  UnveiledLg: "4px",
  Input: "1px",
  Card: "1px",
} as const;
export type Border = (typeof Border)[keyof typeof Border];

export const Shadow = {
  UnveiledSm: "4px 4px 0 0 #202621",
  Unveiled: "6px 6px 0 0 #202621",
  UnveiledLg: "12px 12px 0 0 #202621",
  UnveiledHover: "8px 8px 0 0 #202621",
  UnveiledHoverLg: "16px 16px 0 0 #202621",
} as const;
export type Shadow = (typeof Shadow)[keyof typeof Shadow];

export const Motion = {
  DurationFast: "120ms",
  DurationBase: "180ms",
  DurationSlow: "240ms",
  EasingEaseOut: "ease-out",
  EasingEaseInOut: "ease",
  TransitionCardHover:
    "box-shadow 180ms ease, transform 180ms ease, background-color 180ms ease, color 180ms ease",
} as const;
export type Motion = (typeof Motion)[keyof typeof Motion];

export const Breakpoint = {
  Sm: "640px",
  Md: "768px",
  Lg: "1024px",
  Xl: "1280px",
  "2xl": "1536px",
} as const;
export type Breakpoint = (typeof Breakpoint)[keyof typeof Breakpoint];

export const ZIndex = {
  Base: 0,
  Dropdown: 1000,
  Sticky: 1100,
  Modal: 1300,
  Toast: 1400,
} as const;
export type ZIndex = (typeof ZIndex)[keyof typeof ZIndex];
