/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --config wrangler.toml --include-runtime=false` (hash: 2ea288ed0f8c26654cd6375bd4866f8d)
declare namespace Cloudflare {
  interface Env {
    SESSION: KVNamespace;
    ASSETS_BUCKET: R2Bucket;
    ASSETS: Fetcher;
    BETTER_AUTH_SECRET: string;
    BETTER_AUTH_URL: string;
    PUBLIC_BETTER_AUTH_URL: string;
    PUBLIC_APP_URL: string;
    NODE_ENV: string;
    DATABASE_URL: string;
    RESEND_API_KEY: string;
    DAILY_CODES_FROM_EMAIL: string;
    STRIPE_SECRET_KEY: string;
    STRIPE_WEBHOOK_SECRET: string;
    PUBLIC_STRIPE_PUBLISHABLE_KEY: string;
    STRIPE_PRICE_BASIC_BERLIN: string;
    R2_ACCOUNT_ID: string;
    R2_ACCESS_KEY_ID: string;
    R2_SECRET_ACCESS_KEY: string;
    R2_BUCKET_NAME: string;
    PUBLIC_ASSET_BASE_URL: string;
    CLOUDFLARE_API_TOKEN: string;
    PARITY_TEST_DATABASE_URL: string;
    API: Service /* entrypoint fetch from unveiled-api */;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<
        Cloudflare.Env,
        | "BETTER_AUTH_SECRET"
        | "BETTER_AUTH_URL"
        | "PUBLIC_BETTER_AUTH_URL"
        | "PUBLIC_APP_URL"
        | "NODE_ENV"
        | "DATABASE_URL"
        | "RESEND_API_KEY"
        | "DAILY_CODES_FROM_EMAIL"
        | "STRIPE_SECRET_KEY"
        | "STRIPE_WEBHOOK_SECRET"
        | "PUBLIC_STRIPE_PUBLISHABLE_KEY"
        | "STRIPE_PRICE_BASIC_BERLIN"
        | "R2_ACCOUNT_ID"
        | "R2_ACCESS_KEY_ID"
        | "R2_SECRET_ACCESS_KEY"
        | "R2_BUCKET_NAME"
        | "PUBLIC_ASSET_BASE_URL"
        | "CLOUDFLARE_API_TOKEN"
        | "PARITY_TEST_DATABASE_URL"
      >
    > {}
}
