name = "unveiled"
compatibility_date = "2026-05-06"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public", "no_handle_cross_request_promise_resolution"]
main = "packages/orchestrator/dist/worker.js"
observability = { enabled = true }

assets = { binding = "ASSETS", directory = "./packages/orchestrator/dist/client" }

[[kv_namespaces]]
binding = "SESSION"
id = "b25ac2e3eb4b4df082254d32c7fd6766"
preview_id = "a970664d170d4d18833718fb6b0cd0ee"

[[r2_buckets]]
binding = "ASSETS_BUCKET"
bucket_name = "unveiled-dev"

[[services]]
binding = "APP"
service = "unveiled-app"
entrypoint = "fetch"

[[services]]
binding = "LANDING"
service = "unveiled-landing"
entrypoint = "fetch"

[[services]]
binding = "API"
service = "unveiled-api"
entrypoint = "fetch"