/**
 * Generates CSS custom properties and a typed enum companion from design-tokens.json.
 *
 * Outputs:
 *   - src/styles/generated/tokens.css   : --unveiled-* custom properties on :root
 *   - src/lib/design-tokens.types.ts    : string-literal union types derived from the JSON
 *
 * Run via: bun run tokens:gen
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

const REPO_ROOT = resolve(import.meta.dir, "../../..");
const TOKENS_PATH = join(REPO_ROOT, "design-tokens.json");
const CSS_OUT = join(
  REPO_ROOT,
  "packages/design-system/src/styles/generated/tokens.css",
);
const TYPES_OUT = join(
  REPO_ROOT,
  "packages/design-system/src/lib/design-tokens.types.ts",
);

type TokenNode = Record<string, unknown>;
type ResolvedToken = { name: string; value: string | number; type: string };

function isTokenGroup(value: unknown): value is TokenNode {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isTokenLeaf(
  value: unknown,
): value is { $value: unknown; $type?: string } {
  return (
    typeof value === "object" &&
    value !== null &&
    "$value" in (value as Record<string, unknown>)
  );
}

function tokenCasingToCss(name: string): string {
  return name.replace(/([A-Z])/g, "-$1").toLowerCase();
}

function tokenCasingToTypeMember(name: string): string {
  return name
    .split(/[-_\s]+/)
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join("");
}

function flatten(
  node: TokenNode,
  prefix: string[],
  out: ResolvedToken[],
): void {
  for (const [key, child] of Object.entries(node)) {
    if (key.startsWith("$")) continue;
    const path = [...prefix, key];
    if (isTokenLeaf(child)) {
      const raw = child.$value;
      const type = child.$type ?? "string";
      const value =
        typeof raw === "string" || typeof raw === "number" ? raw : String(raw);
      out.push({ name: path.join("."), value, type });
    } else if (isTokenGroup(child)) {
      flatten(child, path, out);
    }
  }
}

function resolveReferences(flattened: ResolvedToken[]): ResolvedToken[] {
  const lookup = new Map(flattened.map((t) => [t.name, t.value]));
  return flattened.map((token) => {
    if (typeof token.value !== "string") return token;
    const ref = /\{([^}]+)\}/g;
    let value = token.value;
    let prev = "";
    while (prev !== value) {
      prev = value;
      value = value.replace(ref, (_match, refName: string) => {
        const referenced = lookup.get(refName.trim());
        return referenced === undefined ? _match : String(referenced);
      });
    }
    return { ...token, value };
  });
}

function toCssVarName(dotted: string): string {
  const segments = dotted.split(".");
  return `--unveiled-${segments.map(tokenCasingToCss).join("-")}`;
}

function emitCss(resolved: ResolvedToken[]): string {
  const lines: string[] = [
    "/**",
    " * AUTO-GENERATED by scripts/generate-design-tokens.ts. Do not edit by hand.",
    " * Run `bun run tokens:gen` to regenerate, and `bun run tokens:check` to verify drift.",
    " */",
    ":root {",
  ];
  for (const token of resolved) {
    lines.push(`  ${toCssVarName(token.name)}: ${token.value};`);
  }
  lines.push("}", "");
  return lines.join("\n");
}

function _toCssValue(value: string | number): string {
  return typeof value === "number" ? String(value) : value;
}

function toTypeMemberName(dotted: string): string {
  return tokenCasingToTypeMember(dotted.replace(/\./g, "-"));
}

function isValidIdentifier(name: string): boolean {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name);
}

function quoteIfNeeded(name: string): string {
  return isValidIdentifier(name) ? name : JSON.stringify(name);
}

function groupByTopLevel(
  resolved: ResolvedToken[],
): Map<string, ResolvedToken[]> {
  const groups = new Map<string, ResolvedToken[]>();
  for (const token of resolved) {
    const [top, ...rest] = token.name.split(".");
    if (!top) continue;
    if (!groups.has(top)) groups.set(top, []);
    groups.get(top)?.push({ ...token, name: rest.join(".") });
  }
  return groups;
}

function emitTypes(resolved: ResolvedToken[]): string {
  const groups = groupByTopLevel(resolved);
  const lines: string[] = [
    "/**",
    " * AUTO-GENERATED by scripts/generate-design-tokens.ts. Do not edit by hand.",
    " */",
    "",
  ];
  for (const [groupName, tokens] of groups) {
    const typeName = tokenCasingToTypeMember(groupName);
    lines.push(`export const ${typeName} = {`);
    for (const token of tokens) {
      const memberName = toTypeMemberName(token.name);
      const literal =
        typeof token.value === "number"
          ? String(token.value)
          : JSON.stringify(token.value);
      lines.push(`  ${quoteIfNeeded(memberName)}: ${literal},`);
    }
    lines.push("} as const;");
    lines.push(
      `export type ${typeName} = (typeof ${typeName})[keyof typeof ${typeName}];`,
    );
    lines.push("");
  }
  return lines.join("\n");
}

function main(): void {
  const raw = readFileSync(TOKENS_PATH, "utf8");
  const tokens = JSON.parse(raw) as TokenNode;
  const flat: ResolvedToken[] = [];
  flatten(tokens, [], flat);
  const resolved = resolveReferences(flat);

  mkdirSync(dirname(CSS_OUT), { recursive: true });
  mkdirSync(dirname(TYPES_OUT), { recursive: true });
  writeFileSync(CSS_OUT, emitCss(resolved));
  writeFileSync(TYPES_OUT, emitTypes(resolved));

  console.log(`Wrote ${CSS_OUT}`);
  console.log(`Wrote ${TYPES_OUT}`);
}

main();
