import { existsSync, unlinkSync } from "node:fs";

const parityEnvPath = ".env.local";
const generatedMarker =
  "# Generated by scripts/start-parity-dev.ts for Playwright parity tests.";

async function cleanupGeneratedParityEnv() {
  if (!existsSync(parityEnvPath)) return;

  const text = await Bun.file(parityEnvPath).text();
  if (text.startsWith(generatedMarker)) {
    unlinkSync(parityEnvPath);
  }
}

await cleanupGeneratedParityEnv();

const args =
  process.argv.length > 2 ? process.argv.slice(2) : ["test", "tests/parity"];
const child = Bun.spawn(["bunx", "playwright", ...args], {
  stderr: "inherit",
  stdout: "inherit",
});

const exitCode = await child.exited;
await cleanupGeneratedParityEnv();
process.exit(exitCode);
