import "dotenv/config";

import { existsSync, writeFileSync } from "node:fs";

const host = process.argv[2] ?? "127.0.0.1";
const port = process.argv[3] ?? "4322";
const baseURL = `http://${host}:${port}`;
const databaseUrl =
  process.env.PARITY_TEST_DATABASE_URL ?? process.env.DATABASE_URL;
const betterAuthUrl = `${baseURL}/api/auth`;
const parityEnvPath = ".env.local";
const generatedMarker =
  "# Generated by scripts/start-parity-dev.ts for Playwright parity tests.";

if (!databaseUrl) {
  throw new Error(
    "PARITY_TEST_DATABASE_URL or DATABASE_URL is required for parity smoke tests.",
  );
}

console.log(
  `[parity] starting Astro on ${baseURL} with ${
    process.env.PARITY_TEST_DATABASE_URL
      ? "PARITY_TEST_DATABASE_URL"
      : "DATABASE_URL"
  }`,
);

function dotenvValue(value: string) {
  return JSON.stringify(value);
}

const existingParityEnv = existsSync(parityEnvPath)
  ? await Bun.file(parityEnvPath).text()
  : "";

if (existingParityEnv && !existingParityEnv.startsWith(generatedMarker)) {
  throw new Error(
    `${parityEnvPath} already exists. Move it before running parity smoke tests so the launcher can provide parity database overrides.`,
  );
}

writeFileSync(
  parityEnvPath,
  [
    generatedMarker,
    "PARITY_TEST_MODE=1",
    `DATABASE_URL=${dotenvValue(databaseUrl)}`,
    `PARITY_TEST_DATABASE_URL=${dotenvValue(databaseUrl)}`,
    `PUBLIC_APP_URL=${dotenvValue(baseURL)}`,
    `BETTER_AUTH_URL=${dotenvValue(betterAuthUrl)}`,
    `PUBLIC_BETTER_AUTH_URL=${dotenvValue(betterAuthUrl)}`,
    `PUBLIC_GOOGLE_MAPS_API_KEY=${dotenvValue("parity-map-key")}`,
    "",
  ].join("\n"),
);

const child = Bun.spawn(
  ["bunx", "astro", "dev", "--host", host, "--port", port],
  {
    env: {
      ...process.env,
      DATABASE_URL: databaseUrl,
      PARITY_TEST_DATABASE_URL: databaseUrl,
      PARITY_TEST_MODE: "1",
      PUBLIC_APP_URL: baseURL,
      BETTER_AUTH_URL: betterAuthUrl,
      PUBLIC_BETTER_AUTH_URL: betterAuthUrl,
      PUBLIC_GOOGLE_MAPS_API_KEY: "parity-map-key",
    },
    stderr: "inherit",
    stdout: "inherit",
  },
);

for (const signal of ["SIGINT", "SIGTERM"] as const) {
  process.on(signal, () => {
    child.kill(signal);
    process.exit(130);
  });
}

const exitCode = await child.exited;
process.exit(exitCode);
